### ISSUE TITLE
Integrasion appears to be broken after recent HA updates.

### ISSUE THREAD

**Issue by pvarlien** [jonkristian/wasteplan_trv#11]
Logger: homeassistant.components.sensor
Source: custom_components/wasteplan_trv/sensor.py:120
Integration: sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 09:57:22 (6 occurrences)
Last logged: 09:57:30
wasteplan_trv: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wasteplan_trv/sensor.py", line 120, in update
    for entry in self._data.data["calendar"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by pvarlien** [comment]
Or maybe TRV have changed their API.

**Comment by jonkristian** [comment]
Unfortunately I think you are correct, they've changed their API. I've already sent out an email and waiting for a response.

**Comment by jonkristian** [comment]
Fixed in v2.0.0
